task_type: 'contact'
frame_path: ""
mask_path: ""
train_label_path: ""
val_label_path: ""
test_label_path: ""
video_path: ""
data_path: ""
train_val_test_splits: [0.6, 0.2, 0.2]
save_path: "experiments"
save_frames_every: 1

# hyperparameters
num_epoch: 10
batch_size: 64
teacher_forcing_prob: 0.3
first_n_frame_dynamics: 5
frame_interval: 2
learning_rate: 0.0002