task_type: 'contain'
frame_path: "data/contain/frames"
mask_path: "data/contain/mask"
train_label_path: "./train.json"
val_label_path: "./val.json"
test_label_path: "./test.json"
video_path: "./videos"
data_path: "./groundtruth"
train_val_test_splits: [0.6, 0.2, 0.2]
save_path: "experiments"
save_spans: True
load_model_path: "experiments/2021-09-09 04-42-45 contain train pip/model"
experiment_type: "train"
device: "cuda"
model_type: "pip"

# hyperparameters
num_epoch: 1
batch_size: 2
teacher_forcing_prob: 0.1
first_n_frame_dynamics: 3
frame_interval: 2
learning_rate: 0.001
max_seq_len: 40
span_num: 3
seed: 3
