task_type: 'contact'
frame_path: "data/contact/frames"
mask_path: "data/contact/masks"
train_label_path: "./train.json"
val_label_path: "./val.json"
test_label_path: "./test.json"
video_path: "./videos"
data_path: "./groundtruth"
train_val_test_splits: [0.6, 0.2, 0.2]
save_path: "experiments"
save_spans: False
load_model_path: null
experiment_type: "train"
device: "cuda"
model_type: "pip"

# hyperparameters
num_epoch: 20
batch_size: 2
teacher_forcing_prob: 0.1
first_n_frame_dynamics: 3
frame_interval: 2
learning_rate: 0.001
max_seq_len: 40
span_num: 3
seed: 1
